#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”
# Include a custom 404 page that contains a string

REDIRECT_301="\\\trewrite ^/redirect_me https://www.github.com/hafssa01 permanent;"
NOTFOUND_404="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
PATTERN="#error_page 404 /404.html;"


sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $REDIRECT_301" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "47i\ $PATTERN$NOTFOUND_404" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
