#!/usr/bin/env bash

#Displays "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line using a while loop

cnt=0

while [ $cnt -lt 10 ]
do
	if [ $cnt -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( cnt++ ))
done
