#!/usr/bin/env bash

# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays Hi on a new line.

cnt=0

while [ $cnt -lt 10 ]
do
	echo "Best School"
	if [ $cnt -eq 9 ]
	then
		echo "Hi"
	fi
	(( cnt++ ))

done
