#!/usr/bin/env bash

#using while loop from 1 to 10 and:
#displays "bad luck" for the 4th loop iteration
#displays "good luck" for the 8th loop iteration
#displays "Best School" for the other iterations

cnt=1
while [ $cnt -le 10 ]
do
	if [ $cnt -eq 4 ]
	then
		echo "bad luck"
	elif [ $cnt -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( cnt++ ))
done
