#!/usr/bin/env bash
# Usining a while loop to display numbers from 1 to 20
# Displaying specific messages for certain loop iterations using case statement

cnt=1
while [ $cnt -le 20 ]
do
    case $cnt in
        4)
            echo "$cnt and then bad luck from China"
            ;;
        9)
            echo "$cnt and then bad luck from Japan"
            ;;
        17)
            echo "$cnt and then bad luck from Italy"
            ;;
        *)
            echo "$cnt"
            ;;
    esac
    (( cnt++ ))
done
