#!/usr/bin/env bash
# Displays the time for 12 hours and 59 mins.
# Displays hours from 0 to 12
# Displays mins from 1 to 59

hour=0
while [ $hour -lt 12 ]
do
	echo "Hour : $hour"
	min=1
	while [ $min -lt 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hour++ ))
done
